/* This file is autogenerated by SBCManager - DO NOT change anything in this file! */

var sip_interface_address = new Array();
var sip_external_interface_address = new Array();
var sip_interface_port = new Array();
var sip_secure_interface_port = new Array();

sip_interface_address.push("192.168.1.10");
sip_external_interface_address.push("192.168.1.10");
sip_interface_port.push("5060");
sip_secure_interface_port.push("0");

var sip_default_interface_address = "192.168.1.10";
var sip_default_interface_port = "5060";
var sip_default_secure_interface_port = "0";
